#pragma once

enum TEXTYPE	{ TEX_SINGLE, TEX_MULTI, TEX_END };

enum  OBJID { OBJ_TILE, OBJ_MONSTER, OBJ_UI, OBJ_PLAYER, OBJ_END };

enum RENDERID { RENDER_BACKGROUND, RENDER_GAMEOBJECT, RENDER_UI, RENDER_EFFECT, RENDER_END };

enum SCENEID { SC_LOGO, SC_MENU, SC_EDIT, SC_GAME, SC_END };

enum TILEOPT { OPT_PASS, OPT_BLOCK, OPT_END };

